name: CI

on:
  push:
    branches:
      - build_pot3d_custom_mpi_wrappers
  pull_request:
    branches:
      - build_pot3d_custom_mpi_wrappers

env:
  MACOSX_DEPLOYMENT_TARGET: 14.0 
  
jobs:
  Compile_POT3D_with_GFortran:
    name: "Build POT3D and validate"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]  
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2.0.2
        with:
          micromamba-version: '2.0.4-0'
          environment-file: ci/environment.yml

      - name: Verify Environment
        shell: bash -e -x -l {0}
        run: |
          echo "Active Environment: $MAMBA_DEFAULT_ENV"
          which gfortran
          which mpif90

      - name: Install HDF5 via Homebrew (macOS)
        runs-on: macos-latest
        shell: bash -e -x -l {0}
        run: |
          # Install Homebrew if not already installed
          if ! command -v brew &> /dev/null
          then
            echo "Homebrew not found, installing..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

          brew install hdf5
          ls /opt/homebrew/lib | grep hdf5

      - name: Install HDF5 via APT (Ubuntu)
        runs-on: ubuntu-latest  
        shell: bash -e -x -l {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev

      - name: POT3D build only mpi
        runs-on: macos-latest
        shell: bash -e -x -l {0}
        run: |
          # Consider creating OS-specific build scripts if needed
          ./build_examples/build_cpu_mpi-only_gcc_macos_homebrew_lf.sh
          export PATH=$PWD/bin:$PATH 

      - name: POT3D validation
        runs-on: macos-latest
        shell: bash -e -x -l {0}
        run: |
          ./validate.sh

      - name: POT3D build only mpi
        runs-on: ubuntu-latest
        shell: bash -e -x -l {0}
        run: |
          # Consider creating OS-specific build scripts if needed
          ./build_examples/build_cpu_mpi-only_gcc_ubuntu20.04.sh
          export PATH=$PWD/bin:$PATH

      - name: POT3D validation
        runs-on: ubuntu-latest
        shell: bash -e -x -l {0}
        run: |
          ./validate.sh

      - name: POT3D build mpi+multithreaded
        runs-on: ubuntu-latest
        shell: bash -e -x -l {0}
        run: |
          # Consider creating OS-specific build scripts if needed
          ./build_examples/build_cpu_mpi+multithread_gcc_ubuntu20.04.sh
          export PATH=$PWD/bin:$PATH

      - name: POT3D validation
        runs-on: ubuntu-latest
        shell: bash -e -x -l {0}
        run: |
          ./validate.sh